name: Despliegue

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Configura Google Cloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }} # Modificar: Asegúrate de que el ID del proyecto es correcto.
          service_account_key: ${{ secrets.GCP_SA_KEY }} # Modificar: Debe ser la clave de cuenta de servicio correcta y segura.
          export_default_credentials: true
    
      - name: Constuir imagen
        id: docker
        run: |
            docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/cluster-1:${{ github.sha }}
            docker push     gcr.io/${{ secrets.GCP_PROJECT_ID }}/cluster-1:${{ github.sha }}
    
      - name: Despliegue en Kubernetes
        run: |
          kubectl set image deployment/cluster-1 cluster-1=gcr.io/${{ secrets.GCP_PROJECT_ID }}/cluster-1:${{ github.sha }} # Modificar: Asegúrate de que los nombres de los deployments y contenedores son correctos.
          kubectl apply -f .github/workflows/deployment.yml # Modificar: Reemplaza con la ruta correcta al archivo de despliegue de Kubernetes.
